### ISSUE TITLE
Unity crashes when I click "Get dressed!"

### ISSUE THREAD

**Issue by kassixo** [SophieBlueVR/AvatarDresser#3]
![image](https://user-images.githubusercontent.com/25930442/210395531-c368a610-fbc7-443a-809f-1c274bb23149.png)

**Comment by SophieBlueVR** [comment]
Got any more useful info than that?  Any messages in the console?

**Comment by MaximillianCat** [comment]
Same issue.  Here's some additional information and a crash log.  (Crash info at line 1652.)
[Editor.log](https://github.com/SophieBlueVR/AvatarDresser/files/10530463/Editor.log)
Setup seemed simple enough.
![image](https://user-images.githubusercontent.com/29805262/215346006-1fbf31e2-a563-4abc-897c-339e89a5f879.png)
Referenced items out of the project..
![image](https://user-images.githubusercontent.com/29805262/215346037-d336c349-73b5-4982-be66-dac60c7975fe.png)

**Comment by MaximillianCat** [comment]
Managed to crash with my armature that had some custom scaling and rotation AND a factory stock armature.  I may have to try with a fresh project file.

**Comment by SophieBlueVR** [comment]
Oh hey - you seem to be using the `Swimsuits` prefab, but that's just used to get things into your scene.  Per the instructions, you want to drag that prefab into your scene and then unpack it, and then use the Dresser with each individual clothing item.

Maybe I should change the text on the Dresser to not say "Clothing prefab" but "Clothing item" or something instead....

I'll try this myself and see if I can prevent it from crashing at least.

**Comment by MaximillianCat** [comment]
I'll try actually opening the box.  What a silly mistake on my part.

**Comment by MaximillianCat** [comment]
Works correctly if you actually open the prefab in the scene.  So we can chalk this one up to user error.

**Comment by SophieBlueVR** [comment]
Hooray!  Thanks for testing!  I'll update the text a bit :)
