### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by echos0** [SophieBlueVR/AvatarDresser#6]
every time i try adding the clothes with animation it crashes my unity

**Comment by SophieBlueVR** [comment]
I'll need a little more to go on than that, can you provide a lot of the console output?

**Comment by echos0** [comment]
so when i open your auto dresser thing in the tools section in unity and then i add the avatar and then the clothes then check the make animation then i click dress and it crashes thats it

**Comment by SophieBlueVR** [comment]
Okay.    If you could find details in a Unity debug log, I might be able to investigate further, but there's really nothing I can do without understanding why that crash happens.

Sorry about this.

**Comment by echos0** [comment]
Can we talk on discord?
